airports= [
      {"iata_code": "SIN", "city": "Singapore", "name": "Singapore Changi", "country": "Singapore"},
      {"iata_code": "MNL", "city": "Manila", "name": "Ninoy Aquino International", "country": "Philippines"},
      {"iata_code": "DOH", "city": "Doha", "name": "Hamad", "country": "Qatar"},
      {"iata_code": "HND", "city": "Tokyo", "name": "Tokyo Haneda", "country": "Japan"},
      {"iata_code": "ICN", "city": "Seoul", "name": "Incheon", "country": "South Korea"},
      {"iata_code": "CDG", "city": "Paris", "name": "Charles de Gaulle", "country": "France"},
      {"iata_code": "IST", "city": "Istanbul", "name": "Istanbul Airport", "country": "Turkey"},
      {"iata_code": "MUC", "city": "Munich", "name": "Munich Airport", "country": "Germany"},
      {"iata_code": "ZRH", "city": "Zurich", "name": "Zurich Airport", "country": "Switzerland"},
      {"iata_code": "NRT", "city": "Tokyo", "name": "Tokyo Narita", "country": "Japan"},
      {"iata_code": "MAD", "city": "Madrid", "name": "Madrid Barajas", "country": "Spain"},
      {"iata_code": "VIE", "city": "Vienna", "name": "Vienna Airport", "country": "Austria"},
      {"iata_code": "HEL", "city": "Helsinki", "name": "Helsinki-Vantaa Airport", "country": "Finland"},
      {"iata_code": "FCO", "city": "Rome", "name": "Rome Fiumicino Airport", "country": "Italy"},
      {"iata_code": "CPH", "city": "Copenhagen", "name": "Copenhagen Airport", "country": "Denmark"},
      {"iata_code": "KIX", "city": "Osaka", "name": "Kansai International Airport", "country": "Japan"},
      {"iata_code": "NGO", "city": "Nagoya", "name": "Chubu Centrair International Airport", "country": "Japan"},
      {"iata_code": "DXB", "city": "Dubai", "name": "Dubai International Airport", "country": "United Arab Emirates"},
      {"iata_code": "SEA", "city": "Seattle", "name": "Seattle-Tacoma International Airport", "country": "United States"},
      {"iata_code": "MEL", "city": "Melbourne", "name": "Melbourne Airport", "country": "Australia"},
      {"iata_code": "YVR", "city": "Vancouver", "name": "Vancouver International Airport", "country": "Canada"},
      {"iata_code": "DUS", "city": "Dusseldorf", "name": "Dusseldorf Airport", "country": "Germany"},
      {"iata_code": "LHR", "city": "London", "name": "Heathrow Airport", "country": "United Kingdom"},
      {"iata_code": "BNE", "city": "Brisbane", "name": "Brisbane Airport", "country": "Australia"},
      {"iata_code": "CAN", "city": "Guangzhou", "name": "Guangzhou Baiyun International Airport", "country": "China"},
      {"iata_code": "FRA", "city": "Frankfurt", "name": "Frankfurt Airport", "country": "Germany"},
      {"iata_code": "BAH", "city": "Bahrain", "name": "Bahrain International Airport", "country": "Bahrain"},
      {"iata_code": "RUH", "city": "Riyadh", "name": "King Khalid International Airport", "country": "Saudi Arabia"},
      {"iata_code": "HAK", "city": "Haikou", "name": "Haikou Meilan International Airport", "country": "China"},
      {"iata_code": "AMS", "city": "Amsterdam", "name": "Amsterdam Airport Schiphol", "country": "Netherlands"},
      {"iata_code": "FUK", "city": "Fukuoka", "name": "Fukuoka Airport", "country": "Japan"},
      {"iata_code": "SZX", "city": "Shenzhen", "name": "Shenzhen Bao'an International Airport", "country": "China"},
      {"iata_code": "HOU", "city": "Houston", "name": "William P. Hobby Airport", "country": "United States"},
      {"iata_code": "HKG", "city": "Hong Kong", "name": "Hong Kong International Airport", "country": "Hong Kong"},
      {"iata_code": "BCN", "city": "Barcelona", "name": "Barcelona-El Prat Airport", "country": "Spain"},
      {"iata_code": "IAH", "city": "Houston", "name": "George Bush Intercontinental Airport", "country": "United States"},
      {"iata_code": "DEL", "city": "Delhi", "name": "Indira Gandhi International Airport", "country": "India"},
      {"iata_code": "BOG", "city": "Bogota", "name": "El Dorado International Airport", "country": "Colombia"},
      {"iata_code": "HAM", "city": "Hamburg", "name": "Hamburg Airport", "country": "Germany"},
      {"iata_code": "ORY", "city": "Paris", "name": "Paris Orly Airport", "country": "France"},
      {"iata_code": "UIO", "city": "Quito", "name": "Mariscal Sucre International Airport", "country": "Ecuador"},
      {"iata_code": "JED", "city": "Jeddah", "name": "King Abdulaziz International Airport", "country": "Saudi Arabia"},
      {"iata_code": "MCT", "city": "Muscat", "name": "Muscat International Airport", "country": "Oman"},
      {"iata_code": "CGK", "city": "Jakarta", "name": "Soekarno-Hatta International Airport", "country": "Indonesia"},
      {"iata_code": "DMM", "city": "Dammam", "name": "King Fahd International Airport", "country": "Saudi Arabia"},
      {"iata_code": "YUL", "city": "Montreal", "name": "Montreal-Pierre Elliott Trudeau International Airport", "country": "Canada"},
      {"iata_code": "CVG", "city": "Cincinnati", "name": "Cincinnati/Northern Kentucky International Airport", "country": "United States"},
      {"iata_code": "CPT", "city": "Cape Town", "name": "Cape Town International Airport", "country": "South Africa"},
      {"iata_code": "SFO", "city": "San Francisco", "name": "San Francisco International Airport", "country": "United States"},
      {"iata_code": "SYD", "city": "Sydney", "name": "Sydney Kingsford Smith Airport", "country": "Australia"},
      {"iata_code": "SHA", "city": "Shanghai", "name": "Shanghai Hongqiao International Airport", "country": "China"},
      {"iata_code": "AKL", "city": "Auckland", "name": "Auckland Airport", "country": "New Zealand"},
      {"iata_code": "MED", "city": "Madinah", "name": "Prince Mohammad bin Abdulaziz International Airport", "country": "Saudi Arabia"},
      {"iata_code": "GYD", "city": "Baku", "name": "Heydar Aliyev International Airport", "country": "Azerbaijan"},
      {"iata_code": "OOL", "city": "Gold Coast", "name": "Gold Coast Airport", "country": "Australia"},
      {"iata_code": "LGW", "city": "London", "name": "London Gatwick Airport", "country": "United Kingdom"},
      {"iata_code": "CGN", "city": "Cologne", "name": "Cologne Bonn Airport", "country": "Germany"},
      {"iata_code": "LGA", "city": "New York", "name": "LaGuardia Airport", "country": "United States"},
      {"iata_code": "PER", "city": "Perth", "name": "Perth Airport", "country": "Australia"},
      {"iata_code": "CTU", "city": "Chengdu", "name": "Chengdu Tianfu International Airport", "country": "China"},
      {"iata_code": "ATH", "city": "Athens", "name": "Athens International Airport", "country": "Greece"},
      {"iata_code": "DUR", "city": "Durban", "name": "King Shaka International Airport", "country": "South Africa"},
      {"iata_code": "ATL", "city": "Atlanta", "name": "Hartsfield-Jackson Atlanta International Airport", "country": "United States"},
      {"iata_code": "LAX", "city": "Los Angeles", "name": "Los Angeles International Airport", "country": "United States"},
      {"iata_code": "YYZ", "city": "Toronto", "name": "Toronto Pearson International Airport", "country": "Canada"},
      {"iata_code": "HYD", "city": "Hyderabad", "name": "Rajiv Gandhi International Airport", "country": "India"},
      {"iata_code": "DFW", "city": "Dallas/Fort Worth", "name": "Dallas/Fort Worth International Airport", "country": "United States"},
      {"iata_code": "KUL", "city": "Kuala Lumpur", "name": "Kuala Lumpur International Airport", "country": "Malaysia"},
      {"iata_code": "BKK", "city": "Bangkok", "name": "Suvarnabhumi Airport", "country": "Thailand"},
      {"iata_code": "BLR", "city": "Bangalore", "name": "Kempegowda International Airport", "country": "India"},
      {"iata_code": "LCY", "city": "London", "name": "London City Airport", "country": "United Kingdom"},
      {"iata_code": "DEN", "city": "Denver", "name": "Denver International Airport", "country": "United States"},
      {"iata_code": "XIY", "city": "Xi'an", "name": "Xi'an Xianyang International Airport", "country": "China"},
      {"iata_code": "ADL", "city": "Adelaide", "name": "Adelaide Airport", "country": "Australia"},
      {"iata_code": "GMP", "city": "Seoul", "name": "Gimpo International Airport", "country": "South Korea"},
      {"iata_code": "JNB", "city": "Johannesburg", "name": "O.R. Tambo International Airport", "country": "South Africa"},
      {"iata_code": "OSL", "city": "Oslo", "name": "Oslo Gardermoen Airport", "country": "Norway"},
      {"iata_code": "BUD", "city": "Budapest", "name": "Budapest Ferenc Liszt International Airport", "country": "Hungary"},
      {"iata_code": "AGP", "city": "Malaga", "name": "Malaga Costa del Sol Airport", "country": "Spain"},
      {"iata_code": "MLA", "city": "Malta", "name": "Malta International Airport", "country": "Malta"},
      {"iata_code": "DPS", "city": "Denpasar", "name": "Ngurah Rai International Airport", "country": "Indonesia"},
      {"iata_code": "OPO", "city": "Porto", "name": "Francisco Sá Carneiro Airport", "country": "Portugal"},
      {"iata_code": "TPE", "city": "Taipei", "name": "Taiwan Taoyuan International Airport", "country": "Taiwan"},
      {"iata_code": "LIS", "city": "Lisbon", "name": "Lisbon Airport", "country": "Portugal"},
      {"iata_code": "BOM", "city": "Mumbai", "name": "Chhatrapati Shivaji Maharaj International Airport", "country": "India"},
      {"iata_code": "ARN", "city": "Stockholm", "name": "Stockholm Arlanda Airport", "country": "Sweden"},
      {"iata_code": "MXP", "city": "Milan", "name": "Milan Malpensa Airport", "country": "Italy"},
      {"iata_code": "AUH", "city": "Abu Dhabi", "name": "Abu Dhabi International Airport", "country": "United Arab Emirates"},
      {"iata_code": "JFK", "city": "New York", "name": "John F. Kennedy International Airport", "country": "United States"},
      {"iata_code": "LIM", "city": "Lima", "name": "Jorge Chávez International Airport", "country": "Peru"},
      {"iata_code": "ALC", "city": "Alicante", "name": "Alicante-Elche Airport", "country": "Spain"},
      {"iata_code": "PMI", "city": "Palma de Mallorca", "name": "Palma de Mallorca Airport", "country": "Spain"},
      {"iata_code": "YYC", "city": "Calgary", "name": "Calgary International Airport", "country": "Canada"},
      {"iata_code": "KEF", "city": "Keflavik", "name": "Keflavik International Airport", "country": "Iceland"},
      {"iata_code": "PHX", "city": "Phoenix", "name": "Phoenix Sky Harbor International Airport", "country": "United States"},
      {"iata_code": "ITM", "city": "Osaka", "name": "Osaka Itami Airport", "country": "Japan"},
      {"iata_code": "BOS", "city": "Boston", "name": "Logan International Airport", "country": "United States"},
      {"iata_code": "CSX", "city": "Changsha", "name": "Changsha Huanghua International Airport", "country": "China"},
      {"iata_code": "LYS", "city": "Lyon", "name": "Lyon-Saint-Exupéry Airport", "country": "France"},
      {"iata_code": "MSP", "city": "Minneapolis", "name": "Minneapolis-Saint Paul International Airport", "country": "United States"},
      {"iata_code": "CHC", "city": "Christchurch", "name": "Christchurch Airport", "country": "New Zealand"}
    ]
  